Fix broken version code
0.0.4 had a bug that causes this:

      File "/Users/marca/python/virtualenvs/httpie/lib/python2.7/site-packages/pkg_resources.py", line 2184, in load
        ['__name__'])
      File "/Users/marca/python/virtualenvs/httpie/lib/python2.7/site-packages/pytest_httpbin/__init__.py", line 3, in <module>
        with open("pytest_httpbin/version.py") as f:
    IOError: [Errno 2] No such file or directory: 'pytest_httpbin/version.py'